name: Update Bot Code

on:
  push:
    branches: [ main ]
    paths:
      - 'tg_bot/**'
      - '!tg_bot/pdf/**'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update code on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            echo "🚀 Оновлення коду бота..."
            
            # Перехід до директорії проекту
            cd /home/roman/Стільниця/projeckt/tg-onboarding
            
            # Оновлення коду з GitHub
            echo "📥 Отримання оновлень..."
            git pull origin main
            
            # Перехід до директорії бота
            cd tg_bot
            
            # Встановлення залежностей
            echo "📦 Встановлення залежностей..."
            npm ci --only=production
            
            echo "✅ Код оновлено! Тепер потрібно перезапустити бота вручну."
            echo "💡 Виконайте: sudo systemctl restart skillklan-bot"
